// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMS.API.Data;

namespace PIMS.API.Migrations
{
    [DbContext(typeof(PIMSContext))]
    [Migration("20210106040734_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PIMS.API.Domain.Entities.Atoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Atolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "H.A.",
                            Name = "Haa Alif"
                        },
                        new
                        {
                            Id = 2,
                            Code = "H.Dh.",
                            Name = "Haa Dhaalu"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Sh.",
                            Name = "Shaviyani"
                        },
                        new
                        {
                            Id = 4,
                            Code = "N.",
                            Name = "Noonu"
                        },
                        new
                        {
                            Id = 5,
                            Code = "R.",
                            Name = "Raa"
                        },
                        new
                        {
                            Id = 6,
                            Code = "B.",
                            Name = "Baa"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Lh.",
                            Name = "Lhaviyani"
                        },
                        new
                        {
                            Id = 8,
                            Code = "K.",
                            Name = "Kaafu"
                        },
                        new
                        {
                            Id = 9,
                            Code = "A.A.",
                            Name = "North Ari"
                        },
                        new
                        {
                            Id = 10,
                            Code = "A.Dh.",
                            Name = "South Ari"
                        },
                        new
                        {
                            Id = 11,
                            Code = "V.",
                            Name = "Vaavu"
                        },
                        new
                        {
                            Id = 12,
                            Code = "M.",
                            Name = "Meemu"
                        },
                        new
                        {
                            Id = 13,
                            Code = "F.",
                            Name = "Faafu"
                        },
                        new
                        {
                            Id = 14,
                            Code = "Dh.",
                            Name = "Dhaalu"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Th.",
                            Name = "Thaa"
                        },
                        new
                        {
                            Id = 16,
                            Code = "L.",
                            Name = "Laamu"
                        },
                        new
                        {
                            Id = 17,
                            Code = "G.A.",
                            Name = "Gaafu Alif"
                        },
                        new
                        {
                            Id = 18,
                            Code = "G.Dh.",
                            Name = "Gaafu Dhaalu"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Gn.",
                            Name = "Gnaviyani"
                        },
                        new
                        {
                            Id = 20,
                            Code = "S.",
                            Name = "Seenu"
                        });
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TypeId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.CaseFollowup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTime?>("NextFollowupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Case_Followups");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.CaseTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("TypeId");

                    b.ToTable("Case_Tests");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.CaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Case_Types");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AtollId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("AtollId");

                    b.ToTable("Islands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtollId = 1,
                            Name = "Baarah"
                        },
                        new
                        {
                            Id = 2,
                            AtollId = 1,
                            Name = "Dhiddhoo"
                        },
                        new
                        {
                            Id = 3,
                            AtollId = 1,
                            Name = "Filladhoo"
                        },
                        new
                        {
                            Id = 4,
                            AtollId = 1,
                            Name = "Hoarafushi"
                        },
                        new
                        {
                            Id = 5,
                            AtollId = 1,
                            Name = "Ihavandhoo"
                        },
                        new
                        {
                            Id = 6,
                            AtollId = 1,
                            Name = "Kelaa"
                        },
                        new
                        {
                            Id = 7,
                            AtollId = 1,
                            Name = "Maarandhoo"
                        },
                        new
                        {
                            Id = 8,
                            AtollId = 1,
                            Name = "Mulhadhoo"
                        },
                        new
                        {
                            Id = 9,
                            AtollId = 1,
                            Name = "Muraidhoo"
                        },
                        new
                        {
                            Id = 10,
                            AtollId = 1,
                            Name = "Thakandhoo"
                        },
                        new
                        {
                            Id = 11,
                            AtollId = 1,
                            Name = "Thuraakunu"
                        },
                        new
                        {
                            Id = 12,
                            AtollId = 1,
                            Name = "Uligamu"
                        },
                        new
                        {
                            Id = 13,
                            AtollId = 1,
                            Name = "Utheemu"
                        },
                        new
                        {
                            Id = 14,
                            AtollId = 1,
                            Name = "Vashafaru"
                        },
                        new
                        {
                            Id = 15,
                            AtollId = 2,
                            Name = "Hanimaadhoo"
                        },
                        new
                        {
                            Id = 16,
                            AtollId = 2,
                            Name = "Finey"
                        },
                        new
                        {
                            Id = 17,
                            AtollId = 2,
                            Name = "Naivadhoo"
                        },
                        new
                        {
                            Id = 18,
                            AtollId = 2,
                            Name = "Nolhivaranfaru"
                        },
                        new
                        {
                            Id = 19,
                            AtollId = 2,
                            Name = "Nellaidhoo"
                        },
                        new
                        {
                            Id = 20,
                            AtollId = 2,
                            Name = "Nolhivaram"
                        },
                        new
                        {
                            Id = 21,
                            AtollId = 2,
                            Name = "Kurinbi"
                        },
                        new
                        {
                            Id = 22,
                            AtollId = 2,
                            Name = "Kulhudhuffushi"
                        },
                        new
                        {
                            Id = 23,
                            AtollId = 2,
                            Name = "Kumundhoo"
                        },
                        new
                        {
                            Id = 24,
                            AtollId = 2,
                            Name = "Neykurdnedhoo"
                        },
                        new
                        {
                            Id = 25,
                            AtollId = 2,
                            Name = "Vaikaradhoo"
                        },
                        new
                        {
                            Id = 26,
                            AtollId = 2,
                            Name = "Makunudhoo"
                        },
                        new
                        {
                            Id = 27,
                            AtollId = 2,
                            Name = "Hirimaradhoo"
                        },
                        new
                        {
                            Id = 28,
                            AtollId = 3,
                            Name = "Bileffahi"
                        },
                        new
                        {
                            Id = 29,
                            AtollId = 3,
                            Name = "Feevah"
                        },
                        new
                        {
                            Id = 30,
                            AtollId = 3,
                            Name = "Feydhoo"
                        },
                        new
                        {
                            Id = 31,
                            AtollId = 3,
                            Name = "Foakaidhoo"
                        },
                        new
                        {
                            Id = 32,
                            AtollId = 3,
                            Name = "Funadhoo"
                        },
                        new
                        {
                            Id = 33,
                            AtollId = 3,
                            Name = "Goidhoo"
                        },
                        new
                        {
                            Id = 34,
                            AtollId = 3,
                            Name = "Kanditheemu"
                        },
                        new
                        {
                            Id = 35,
                            AtollId = 3,
                            Name = "Komandoo"
                        },
                        new
                        {
                            Id = 36,
                            AtollId = 3,
                            Name = "Lhaimagu"
                        },
                        new
                        {
                            Id = 37,
                            AtollId = 3,
                            Name = "Maaungoodhoo"
                        },
                        new
                        {
                            Id = 38,
                            AtollId = 3,
                            Name = "Maroshi"
                        },
                        new
                        {
                            Id = 39,
                            AtollId = 3,
                            Name = "Milandhoo"
                        },
                        new
                        {
                            Id = 40,
                            AtollId = 3,
                            Name = "Narudhoo"
                        },
                        new
                        {
                            Id = 41,
                            AtollId = 3,
                            Name = "Noomaraa"
                        },
                        new
                        {
                            Id = 42,
                            AtollId = 4,
                            Name = "Foddhoo"
                        },
                        new
                        {
                            Id = 43,
                            AtollId = 4,
                            Name = "Henbandhoo"
                        },
                        new
                        {
                            Id = 44,
                            AtollId = 4,
                            Name = "Holhudhoo"
                        },
                        new
                        {
                            Id = 45,
                            AtollId = 4,
                            Name = "Kendhikulhudhoo"
                        },
                        new
                        {
                            Id = 46,
                            AtollId = 4,
                            Name = "Kudafari"
                        },
                        new
                        {
                            Id = 47,
                            AtollId = 4,
                            Name = "Landhoo"
                        },
                        new
                        {
                            Id = 48,
                            AtollId = 4,
                            Name = "Lhohi"
                        },
                        new
                        {
                            Id = 49,
                            AtollId = 4,
                            Name = "Maafaru"
                        },
                        new
                        {
                            Id = 50,
                            AtollId = 4,
                            Name = "Maalhendhoo"
                        },
                        new
                        {
                            Id = 51,
                            AtollId = 4,
                            Name = "Magoodhoo"
                        },
                        new
                        {
                            Id = 52,
                            AtollId = 4,
                            Name = "Manadhoo "
                        },
                        new
                        {
                            Id = 53,
                            AtollId = 4,
                            Name = "Miladhoo"
                        },
                        new
                        {
                            Id = 54,
                            AtollId = 4,
                            Name = "Velidhoo"
                        },
                        new
                        {
                            Id = 55,
                            AtollId = 5,
                            Name = "Alifushi"
                        },
                        new
                        {
                            Id = 56,
                            AtollId = 5,
                            Name = "Angolhitheemu"
                        },
                        new
                        {
                            Id = 57,
                            AtollId = 5,
                            Name = "Fainu"
                        },
                        new
                        {
                            Id = 58,
                            AtollId = 5,
                            Name = "Hulhudhuffaaru"
                        },
                        new
                        {
                            Id = 59,
                            AtollId = 5,
                            Name = "Inguraidhoo"
                        },
                        new
                        {
                            Id = 60,
                            AtollId = 5,
                            Name = "Innamaadhoo"
                        },
                        new
                        {
                            Id = 61,
                            AtollId = 5,
                            Name = "Dhuvaafaru"
                        },
                        new
                        {
                            Id = 62,
                            AtollId = 5,
                            Name = "Kinolhas"
                        },
                        new
                        {
                            Id = 63,
                            AtollId = 5,
                            Name = "Maakurathu"
                        },
                        new
                        {
                            Id = 64,
                            AtollId = 5,
                            Name = "Maduvvaree"
                        },
                        new
                        {
                            Id = 65,
                            AtollId = 5,
                            Name = "Meedhoo"
                        },
                        new
                        {
                            Id = 66,
                            AtollId = 5,
                            Name = "Rasgetheemu"
                        },
                        new
                        {
                            Id = 67,
                            AtollId = 5,
                            Name = "Rasmaadhoo"
                        },
                        new
                        {
                            Id = 68,
                            AtollId = 5,
                            Name = "Ungoofaaru"
                        },
                        new
                        {
                            Id = 69,
                            AtollId = 5,
                            Name = "Vaadhoo"
                        },
                        new
                        {
                            Id = 70,
                            AtollId = 6,
                            Name = "Dharavandhoo"
                        },
                        new
                        {
                            Id = 71,
                            AtollId = 6,
                            Name = "Dhonfanu"
                        },
                        new
                        {
                            Id = 72,
                            AtollId = 6,
                            Name = "Eydhafushi "
                        },
                        new
                        {
                            Id = 73,
                            AtollId = 6,
                            Name = "Fehendhoo"
                        },
                        new
                        {
                            Id = 74,
                            AtollId = 6,
                            Name = "Fulhadhoo"
                        },
                        new
                        {
                            Id = 75,
                            AtollId = 6,
                            Name = "Goidhoo"
                        },
                        new
                        {
                            Id = 76,
                            AtollId = 6,
                            Name = "Hithaadhoo"
                        },
                        new
                        {
                            Id = 77,
                            AtollId = 6,
                            Name = "Kamadhoo"
                        },
                        new
                        {
                            Id = 78,
                            AtollId = 6,
                            Name = "Kendhoo"
                        },
                        new
                        {
                            Id = 79,
                            AtollId = 6,
                            Name = "Kihaadhoo"
                        },
                        new
                        {
                            Id = 80,
                            AtollId = 6,
                            Name = "Kudarikilu"
                        },
                        new
                        {
                            Id = 81,
                            AtollId = 6,
                            Name = "Maalhos"
                        },
                        new
                        {
                            Id = 82,
                            AtollId = 6,
                            Name = "Thulhaadhoo"
                        },
                        new
                        {
                            Id = 83,
                            AtollId = 7,
                            Name = "Hinnavaru"
                        },
                        new
                        {
                            Id = 84,
                            AtollId = 7,
                            Name = "Kurendhoo"
                        },
                        new
                        {
                            Id = 85,
                            AtollId = 7,
                            Name = "Maafilaafushi"
                        },
                        new
                        {
                            Id = 86,
                            AtollId = 7,
                            Name = "Naifaru "
                        },
                        new
                        {
                            Id = 87,
                            AtollId = 7,
                            Name = "Olhuvelifushi"
                        },
                        new
                        {
                            Id = 88,
                            AtollId = 8,
                            Name = "Dhiffushi"
                        },
                        new
                        {
                            Id = 89,
                            AtollId = 8,
                            Name = "Gaafaru"
                        },
                        new
                        {
                            Id = 90,
                            AtollId = 8,
                            Name = "Gulhi"
                        },
                        new
                        {
                            Id = 91,
                            AtollId = 8,
                            Name = "Guraidhoo"
                        },
                        new
                        {
                            Id = 92,
                            AtollId = 8,
                            Name = "Himmafushi"
                        },
                        new
                        {
                            Id = 93,
                            AtollId = 8,
                            Name = "Hulhumalé"
                        },
                        new
                        {
                            Id = 94,
                            AtollId = 8,
                            Name = "Huraa"
                        },
                        new
                        {
                            Id = 95,
                            AtollId = 8,
                            Name = "Kaashidhoo"
                        },
                        new
                        {
                            Id = 96,
                            AtollId = 8,
                            Name = "Malé "
                        },
                        new
                        {
                            Id = 97,
                            AtollId = 8,
                            Name = "Maafushi "
                        },
                        new
                        {
                            Id = 98,
                            AtollId = 8,
                            Name = "Thulusdhoo "
                        },
                        new
                        {
                            Id = 99,
                            AtollId = 8,
                            Name = "Vilimalé "
                        },
                        new
                        {
                            Id = 100,
                            AtollId = 9,
                            Name = "Bodufolhudhoo"
                        },
                        new
                        {
                            Id = 101,
                            AtollId = 9,
                            Name = "Feridhoo"
                        },
                        new
                        {
                            Id = 102,
                            AtollId = 9,
                            Name = "Himandhoo"
                        },
                        new
                        {
                            Id = 103,
                            AtollId = 9,
                            Name = "Maalhos"
                        },
                        new
                        {
                            Id = 104,
                            AtollId = 9,
                            Name = "Mathiveri"
                        },
                        new
                        {
                            Id = 105,
                            AtollId = 9,
                            Name = "Rasdhoo"
                        },
                        new
                        {
                            Id = 106,
                            AtollId = 9,
                            Name = "Thoddoo"
                        },
                        new
                        {
                            Id = 107,
                            AtollId = 9,
                            Name = "Ukulhas"
                        },
                        new
                        {
                            Id = 108,
                            AtollId = 9,
                            Name = "Fesdhoo"
                        },
                        new
                        {
                            Id = 109,
                            AtollId = 10,
                            Name = "Dhangethi"
                        },
                        new
                        {
                            Id = 110,
                            AtollId = 10,
                            Name = "Dhiddhoo"
                        },
                        new
                        {
                            Id = 111,
                            AtollId = 10,
                            Name = "Dhigurah"
                        },
                        new
                        {
                            Id = 112,
                            AtollId = 10,
                            Name = "Fenfushi"
                        },
                        new
                        {
                            Id = 113,
                            AtollId = 10,
                            Name = "Haggnaameedhoo"
                        },
                        new
                        {
                            Id = 114,
                            AtollId = 10,
                            Name = "Kunburudhoo"
                        },
                        new
                        {
                            Id = 115,
                            AtollId = 10,
                            Name = "Maamingili"
                        },
                        new
                        {
                            Id = 116,
                            AtollId = 10,
                            Name = "Mahibadhoo "
                        },
                        new
                        {
                            Id = 117,
                            AtollId = 10,
                            Name = "Mandhoo"
                        },
                        new
                        {
                            Id = 118,
                            AtollId = 10,
                            Name = "Omadhoo"
                        },
                        new
                        {
                            Id = 119,
                            AtollId = 11,
                            Name = "Felidhoo "
                        },
                        new
                        {
                            Id = 120,
                            AtollId = 11,
                            Name = "Fulidhoo"
                        },
                        new
                        {
                            Id = 121,
                            AtollId = 11,
                            Name = "Keyodhoo"
                        },
                        new
                        {
                            Id = 122,
                            AtollId = 11,
                            Name = "Rakeedhoo"
                        },
                        new
                        {
                            Id = 123,
                            AtollId = 11,
                            Name = "Thinadhoo"
                        },
                        new
                        {
                            Id = 124,
                            AtollId = 12,
                            Name = "Boli Mulah"
                        },
                        new
                        {
                            Id = 125,
                            AtollId = 12,
                            Name = "Dhiggaru"
                        },
                        new
                        {
                            Id = 126,
                            AtollId = 12,
                            Name = "Kolhufushi"
                        },
                        new
                        {
                            Id = 127,
                            AtollId = 12,
                            Name = "Madifushi"
                        },
                        new
                        {
                            Id = 128,
                            AtollId = 12,
                            Name = "Maduvvaree"
                        },
                        new
                        {
                            Id = 129,
                            AtollId = 12,
                            Name = "Muli "
                        },
                        new
                        {
                            Id = 130,
                            AtollId = 12,
                            Name = "Naalaafushi"
                        },
                        new
                        {
                            Id = 131,
                            AtollId = 12,
                            Name = "Raimmandhoo"
                        },
                        new
                        {
                            Id = 132,
                            AtollId = 12,
                            Name = "Veyvah"
                        },
                        new
                        {
                            Id = 133,
                            AtollId = 13,
                            Name = "Bileddhoo"
                        },
                        new
                        {
                            Id = 134,
                            AtollId = 13,
                            Name = "Dharanboodhoo"
                        },
                        new
                        {
                            Id = 135,
                            AtollId = 13,
                            Name = "Feeali"
                        },
                        new
                        {
                            Id = 136,
                            AtollId = 13,
                            Name = "Magoodhoo"
                        },
                        new
                        {
                            Id = 137,
                            AtollId = 13,
                            Name = "Nilandhoo"
                        },
                        new
                        {
                            Id = 138,
                            AtollId = 14,
                            Name = "Bandidhoo"
                        },
                        new
                        {
                            Id = 139,
                            AtollId = 14,
                            Name = "Gemendhoo"
                        },
                        new
                        {
                            Id = 140,
                            AtollId = 14,
                            Name = "Hulhudheli"
                        },
                        new
                        {
                            Id = 141,
                            AtollId = 14,
                            Name = "Kudahuvadhoo "
                        },
                        new
                        {
                            Id = 142,
                            AtollId = 14,
                            Name = "Maaenboodhoo"
                        },
                        new
                        {
                            Id = 143,
                            AtollId = 14,
                            Name = "Meedhoo"
                        },
                        new
                        {
                            Id = 144,
                            AtollId = 14,
                            Name = "Rinbudhoo"
                        },
                        new
                        {
                            Id = 145,
                            AtollId = 14,
                            Name = "Vaanee"
                        },
                        new
                        {
                            Id = 146,
                            AtollId = 15,
                            Name = "Burunee"
                        },
                        new
                        {
                            Id = 147,
                            AtollId = 15,
                            Name = "Vilufushi"
                        },
                        new
                        {
                            Id = 148,
                            AtollId = 15,
                            Name = "Madifushi"
                        },
                        new
                        {
                            Id = 149,
                            AtollId = 15,
                            Name = "Dhiyamingili"
                        },
                        new
                        {
                            Id = 150,
                            AtollId = 15,
                            Name = "Guraidhoo"
                        },
                        new
                        {
                            Id = 151,
                            AtollId = 15,
                            Name = "Gaadhiffushi"
                        },
                        new
                        {
                            Id = 152,
                            AtollId = 15,
                            Name = "Thimarafushi"
                        },
                        new
                        {
                            Id = 153,
                            AtollId = 15,
                            Name = "Veymandoo "
                        },
                        new
                        {
                            Id = 154,
                            AtollId = 15,
                            Name = "Kinbidhoo"
                        },
                        new
                        {
                            Id = 155,
                            AtollId = 15,
                            Name = "Omadhoo"
                        },
                        new
                        {
                            Id = 156,
                            AtollId = 15,
                            Name = "Hirilandhoo"
                        },
                        new
                        {
                            Id = 157,
                            AtollId = 15,
                            Name = "Kandoodhoo"
                        },
                        new
                        {
                            Id = 158,
                            AtollId = 15,
                            Name = "Vandhoo"
                        },
                        new
                        {
                            Id = 159,
                            AtollId = 16,
                            Name = "Dhanbidhoo"
                        },
                        new
                        {
                            Id = 160,
                            AtollId = 16,
                            Name = "Fonadhoo "
                        },
                        new
                        {
                            Id = 161,
                            AtollId = 16,
                            Name = "Gan"
                        },
                        new
                        {
                            Id = 162,
                            AtollId = 16,
                            Name = "Hithadhoo"
                        },
                        new
                        {
                            Id = 163,
                            AtollId = 16,
                            Name = "Isdhoo"
                        },
                        new
                        {
                            Id = 164,
                            AtollId = 16,
                            Name = "Kunahandhoo"
                        },
                        new
                        {
                            Id = 165,
                            AtollId = 16,
                            Name = "Maabaidhoo"
                        },
                        new
                        {
                            Id = 166,
                            AtollId = 16,
                            Name = "Maamendhoo"
                        },
                        new
                        {
                            Id = 167,
                            AtollId = 16,
                            Name = "Maavah"
                        },
                        new
                        {
                            Id = 168,
                            AtollId = 16,
                            Name = "Mundoo"
                        },
                        new
                        {
                            Id = 169,
                            AtollId = 17,
                            Name = "Dhaandhoo"
                        },
                        new
                        {
                            Id = 170,
                            AtollId = 17,
                            Name = "Dhevvadhoo"
                        },
                        new
                        {
                            Id = 171,
                            AtollId = 17,
                            Name = "Gemanafushi"
                        },
                        new
                        {
                            Id = 172,
                            AtollId = 17,
                            Name = "Kanduhulhudhoo"
                        },
                        new
                        {
                            Id = 173,
                            AtollId = 17,
                            Name = "Kolamaafushi"
                        },
                        new
                        {
                            Id = 174,
                            AtollId = 17,
                            Name = "Kondey"
                        },
                        new
                        {
                            Id = 175,
                            AtollId = 17,
                            Name = "Maamendhoo"
                        },
                        new
                        {
                            Id = 176,
                            AtollId = 17,
                            Name = "Nilandhoo"
                        },
                        new
                        {
                            Id = 177,
                            AtollId = 17,
                            Name = "Villingili"
                        },
                        new
                        {
                            Id = 178,
                            AtollId = 18,
                            Name = "Fares-Maathodaa"
                        },
                        new
                        {
                            Id = 179,
                            AtollId = 18,
                            Name = "Fiyoaree"
                        },
                        new
                        {
                            Id = 180,
                            AtollId = 18,
                            Name = "Gaddhoo"
                        },
                        new
                        {
                            Id = 181,
                            AtollId = 18,
                            Name = "Hoandeddhoo"
                        },
                        new
                        {
                            Id = 182,
                            AtollId = 18,
                            Name = "Madaveli"
                        },
                        new
                        {
                            Id = 183,
                            AtollId = 18,
                            Name = "Nadellaa"
                        },
                        new
                        {
                            Id = 184,
                            AtollId = 18,
                            Name = "Rathafandhoo"
                        },
                        new
                        {
                            Id = 185,
                            AtollId = 18,
                            Name = "Thinadhoo "
                        },
                        new
                        {
                            Id = 186,
                            AtollId = 18,
                            Name = "Vaadhoo"
                        },
                        new
                        {
                            Id = 187,
                            AtollId = 19,
                            Name = "Fuvahmulah"
                        },
                        new
                        {
                            Id = 188,
                            AtollId = 20,
                            Name = "Hithadhoo "
                        },
                        new
                        {
                            Id = 189,
                            AtollId = 20,
                            Name = "Maradhoo"
                        },
                        new
                        {
                            Id = 190,
                            AtollId = 20,
                            Name = "Maradhoo-Feydhoo "
                        },
                        new
                        {
                            Id = 191,
                            AtollId = 20,
                            Name = "Feydhoo"
                        },
                        new
                        {
                            Id = 192,
                            AtollId = 20,
                            Name = "Hulhudhoo"
                        },
                        new
                        {
                            Id = 193,
                            AtollId = 20,
                            Name = "Meedhoo"
                        });
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenericName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.MedicineRequisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AmountRemaining")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DispatchedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("DispatchedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FDAB")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RecievedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("RecievedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("VendorId");

                    b.ToTable("Medicine_Requisitions");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.MedicineVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("PrimaryContactNumber")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryContactNumber")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicine_Vendors");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("HospitalNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("IslandId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryContactNumber")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("SecondaryContactNumber")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalNumber")
                        .IsUnique()
                        .HasFilter("[HospitalNumber] IS NOT NULL");

                    b.HasIndex("Identification")
                        .IsUnique();

                    b.HasIndex("IslandId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasFilter("[RegistrationNumber] IS NOT NULL");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.PatientHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CancerTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Familial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Surgical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Patient_Histories");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.TestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Test_Types");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Case", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Patient", "Patient")
                        .WithMany("Cases")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMS.API.Domain.Entities.CaseType", "Type")
                        .WithMany("Cases")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.CaseFollowup", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Case", "Case")
                        .WithMany("Followups")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.CaseTest", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Case", "Case")
                        .WithMany("Tests")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMS.API.Domain.Entities.TestType", "Type")
                        .WithMany("CaseTests")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Island", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Atoll", "Atoll")
                        .WithMany("Islands")
                        .HasForeignKey("AtollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atoll");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.MedicineRequisition", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Case", "Case")
                        .WithMany("Medicines")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMS.API.Domain.Entities.Medicine", "Medicine")
                        .WithMany("Requisitions")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMS.API.Domain.Entities.MedicineVendor", "Vendor")
                        .WithMany("Requisitions")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Medicine");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Patient", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Island", "Island")
                        .WithMany("Patients")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Island");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.PatientHistory", b =>
                {
                    b.HasOne("PIMS.API.Domain.Entities.Patient", "Patient")
                        .WithOne("History")
                        .HasForeignKey("PIMS.API.Domain.Entities.PatientHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Atoll", b =>
                {
                    b.Navigation("Islands");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Case", b =>
                {
                    b.Navigation("Followups");

                    b.Navigation("Medicines");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.CaseType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Island", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Medicine", b =>
                {
                    b.Navigation("Requisitions");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.MedicineVendor", b =>
                {
                    b.Navigation("Requisitions");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("History");
                });

            modelBuilder.Entity("PIMS.API.Domain.Entities.TestType", b =>
                {
                    b.Navigation("CaseTests");
                });
#pragma warning restore 612, 618
        }
    }
}
